# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dima\PyFiles\MedNN\qt_cpp_project\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(942, 686)
        MainWindow.setMinimumSize(QtCore.QSize(650, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(615, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_open = QtWidgets.QWidget()
        self.tab_open.setObjectName("tab_open")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_open)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_open)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t0_le_openMeta = QtWidgets.QLineEdit(self.groupBox)
        self.t0_le_openMeta.setObjectName("t0_le_openMeta")
        self.horizontalLayout_2.addWidget(self.t0_le_openMeta)
        self.t0_btn_openMeta = QtWidgets.QToolButton(self.groupBox)
        self.t0_btn_openMeta.setObjectName("t0_btn_openMeta")
        self.horizontalLayout_2.addWidget(self.t0_btn_openMeta)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.t0_lbl_foundMeta_l = QtWidgets.QLabel(self.groupBox)
        self.t0_lbl_foundMeta_l.setEnabled(False)
        self.t0_lbl_foundMeta_l.setObjectName("t0_lbl_foundMeta_l")
        self.horizontalLayout_2.addWidget(self.t0_lbl_foundMeta_l)
        self.t0_sb_foundMeta = QtWidgets.QSpinBox(self.groupBox)
        self.t0_sb_foundMeta.setEnabled(False)
        self.t0_sb_foundMeta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t0_sb_foundMeta.setReadOnly(True)
        self.t0_sb_foundMeta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_foundMeta.setProperty("showGroupSeparator", True)
        self.t0_sb_foundMeta.setObjectName("t0_sb_foundMeta")
        self.horizontalLayout_2.addWidget(self.t0_sb_foundMeta)
        self.t0_lbl_foundMeta_r = QtWidgets.QLabel(self.groupBox)
        self.t0_lbl_foundMeta_r.setEnabled(False)
        self.t0_lbl_foundMeta_r.setObjectName("t0_lbl_foundMeta_r")
        self.horizontalLayout_2.addWidget(self.t0_lbl_foundMeta_r)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(self.tab_open)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.t0_radio_yes = QtWidgets.QRadioButton(self.tab_open)
        self.t0_radio_yes.setObjectName("t0_radio_yes")
        self.horizontalLayout_3.addWidget(self.t0_radio_yes)
        self.t0_radio_no = QtWidgets.QRadioButton(self.tab_open)
        self.t0_radio_no.setObjectName("t0_radio_no")
        self.horizontalLayout_3.addWidget(self.t0_radio_no)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.t0_gb_autoSplit = QtWidgets.QGroupBox(self.tab_open)
        self.t0_gb_autoSplit.setEnabled(False)
        self.t0_gb_autoSplit.setObjectName("t0_gb_autoSplit")
        self.gridLayout = QtWidgets.QGridLayout(self.t0_gb_autoSplit)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.t0_gb_autoSplit)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.t0_le_openTrain = QtWidgets.QLineEdit(self.t0_gb_autoSplit)
        self.t0_le_openTrain.setObjectName("t0_le_openTrain")
        self.gridLayout.addWidget(self.t0_le_openTrain, 0, 1, 1, 1)
        self.t0_btn_openTrain = QtWidgets.QToolButton(self.t0_gb_autoSplit)
        self.t0_btn_openTrain.setObjectName("t0_btn_openTrain")
        self.gridLayout.addWidget(self.t0_btn_openTrain, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.t0_gb_autoSplit)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.t0_le_openTest = QtWidgets.QLineEdit(self.t0_gb_autoSplit)
        self.t0_le_openTest.setObjectName("t0_le_openTest")
        self.gridLayout.addWidget(self.t0_le_openTest, 1, 1, 1, 1)
        self.t0_btn_openTest = QtWidgets.QToolButton(self.t0_gb_autoSplit)
        self.t0_btn_openTest.setObjectName("t0_btn_openTest")
        self.gridLayout.addWidget(self.t0_btn_openTest, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.t0_gb_autoSplit)
        self.t0_gb_manualSplit = QtWidgets.QGroupBox(self.tab_open)
        self.t0_gb_manualSplit.setEnabled(False)
        self.t0_gb_manualSplit.setObjectName("t0_gb_manualSplit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.t0_gb_manualSplit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.t0_gb_manualSplit)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.t0_le_openImg = QtWidgets.QLineEdit(self.t0_gb_manualSplit)
        self.t0_le_openImg.setObjectName("t0_le_openImg")
        self.horizontalLayout_4.addWidget(self.t0_le_openImg)
        self.t0_btn_openImg = QtWidgets.QToolButton(self.t0_gb_manualSplit)
        self.t0_btn_openImg.setObjectName("t0_btn_openImg")
        self.horizontalLayout_4.addWidget(self.t0_btn_openImg)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.t0_gb_manualSplit)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.t0_sldr_trainSize = QtWidgets.QSlider(self.t0_gb_manualSplit)
        self.t0_sldr_trainSize.setMaximum(100)
        self.t0_sldr_trainSize.setOrientation(QtCore.Qt.Horizontal)
        self.t0_sldr_trainSize.setObjectName("t0_sldr_trainSize")
        self.horizontalLayout_5.addWidget(self.t0_sldr_trainSize)
        self.t0_sb_trainSize = QtWidgets.QSpinBox(self.t0_gb_manualSplit)
        self.t0_sb_trainSize.setReadOnly(True)
        self.t0_sb_trainSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_trainSize.setMaximum(100)
        self.t0_sb_trainSize.setObjectName("t0_sb_trainSize")
        self.horizontalLayout_5.addWidget(self.t0_sb_trainSize)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.t0_gb_manualSplit)
        self.line_2 = QtWidgets.QFrame(self.tab_open)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.t0_lbl_foundClasses_l = QtWidgets.QLabel(self.tab_open)
        self.t0_lbl_foundClasses_l.setObjectName("t0_lbl_foundClasses_l")
        self.horizontalLayout_6.addWidget(self.t0_lbl_foundClasses_l)
        self.t0_sb_foundClasses = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_foundClasses.setAlignment(QtCore.Qt.AlignCenter)
        self.t0_sb_foundClasses.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_foundClasses.setObjectName("t0_sb_foundClasses")
        self.horizontalLayout_6.addWidget(self.t0_sb_foundClasses)
        self.t0_lbl_foundClasses_r = QtWidgets.QLabel(self.tab_open)
        self.t0_lbl_foundClasses_r.setObjectName("t0_lbl_foundClasses_r")
        self.horizontalLayout_6.addWidget(self.t0_lbl_foundClasses_r)
        self.t0_btn_classesInfo = QtWidgets.QPushButton(self.tab_open)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t0_btn_classesInfo.sizePolicy().hasHeightForWidth())
        self.t0_btn_classesInfo.setSizePolicy(sizePolicy)
        self.t0_btn_classesInfo.setMaximumSize(QtCore.QSize(20, 16777215))
        self.t0_btn_classesInfo.setObjectName("t0_btn_classesInfo")
        self.horizontalLayout_6.addWidget(self.t0_btn_classesInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t0_lbl_trainPlot = QtWidgets.QLabel(self.tab_open)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t0_lbl_trainPlot.setFont(font)
        self.t0_lbl_trainPlot.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.t0_lbl_trainPlot.setObjectName("t0_lbl_trainPlot")
        self.verticalLayout_3.addWidget(self.t0_lbl_trainPlot)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.t0_sb_countTrain_perc = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTrain_perc.setReadOnly(True)
        self.t0_sb_countTrain_perc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTrain_perc.setMaximum(100)
        self.t0_sb_countTrain_perc.setObjectName("t0_sb_countTrain_perc")
        self.horizontalLayout.addWidget(self.t0_sb_countTrain_perc)
        self.label_4 = QtWidgets.QLabel(self.tab_open)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.t0_sb_countTrain = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTrain.setMinimumSize(QtCore.QSize(38, 0))
        self.t0_sb_countTrain.setReadOnly(True)
        self.t0_sb_countTrain.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTrain.setProperty("showGroupSeparator", True)
        self.t0_sb_countTrain.setSuffix("")
        self.t0_sb_countTrain.setPrefix("")
        self.t0_sb_countTrain.setObjectName("t0_sb_countTrain")
        self.horizontalLayout.addWidget(self.t0_sb_countTrain)
        self.label_5 = QtWidgets.QLabel(self.tab_open)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.tab_open)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.t0_lbl_testPlot = QtWidgets.QLabel(self.tab_open)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t0_lbl_testPlot.setFont(font)
        self.t0_lbl_testPlot.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.t0_lbl_testPlot.setObjectName("t0_lbl_testPlot")
        self.verticalLayout_4.addWidget(self.t0_lbl_testPlot)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.t0_sb_countTest_perc = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTest_perc.setReadOnly(True)
        self.t0_sb_countTest_perc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTest_perc.setMaximum(100)
        self.t0_sb_countTest_perc.setObjectName("t0_sb_countTest_perc")
        self.horizontalLayout_7.addWidget(self.t0_sb_countTest_perc)
        self.label_8 = QtWidgets.QLabel(self.tab_open)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.t0_sb_countTest = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTest.setMinimumSize(QtCore.QSize(38, 0))
        self.t0_sb_countTest.setReadOnly(True)
        self.t0_sb_countTest.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTest.setProperty("showGroupSeparator", True)
        self.t0_sb_countTest.setSuffix("")
        self.t0_sb_countTest.setPrefix("")
        self.t0_sb_countTest.setObjectName("t0_sb_countTest")
        self.horizontalLayout_7.addWidget(self.t0_sb_countTest)
        self.label_9 = QtWidgets.QLabel(self.tab_open)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.t0_btn_next = QtWidgets.QPushButton(self.tab_open)
        self.t0_btn_next.setObjectName("t0_btn_next")
        self.horizontalLayout_8.addWidget(self.t0_btn_next)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_open, "")
        self.tab_balance = QtWidgets.QWidget()
        self.tab_balance.setObjectName("tab_balance")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_balance)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.tab_balance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.t1_lyt_plot = QtWidgets.QVBoxLayout()
        self.t1_lyt_plot.setObjectName("t1_lyt_plot")
        self.verticalLayout_8.addLayout(self.t1_lyt_plot)
        self.line_4 = QtWidgets.QFrame(self.tab_balance)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.t1_radio_no_changes = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_no_changes.setObjectName("t1_radio_no_changes")
        self.verticalLayout_8.addWidget(self.t1_radio_no_changes)
        self.t1_radio_enrichMin = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_enrichMin.setObjectName("t1_radio_enrichMin")
        self.verticalLayout_8.addWidget(self.t1_radio_enrichMin)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.t1_lbl_enrichMin = QtWidgets.QLabel(self.tab_balance)
        self.t1_lbl_enrichMin.setEnabled(False)
        self.t1_lbl_enrichMin.setObjectName("t1_lbl_enrichMin")
        self.horizontalLayout_10.addWidget(self.t1_lbl_enrichMin)
        self.t1_sb_enrichMin = QtWidgets.QSpinBox(self.tab_balance)
        self.t1_sb_enrichMin.setEnabled(False)
        self.t1_sb_enrichMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t1_sb_enrichMin.setProperty("showGroupSeparator", True)
        self.t1_sb_enrichMin.setMaximum(10000)
        self.t1_sb_enrichMin.setObjectName("t1_sb_enrichMin")
        self.horizontalLayout_10.addWidget(self.t1_sb_enrichMin)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.t1_radio_enrichMax = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_enrichMax.setObjectName("t1_radio_enrichMax")
        self.verticalLayout_8.addWidget(self.t1_radio_enrichMax)
        self.t1_twgt = QtWidgets.QTableWidget(self.tab_balance)
        self.t1_twgt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_twgt.sizePolicy().hasHeightForWidth())
        self.t1_twgt.setSizePolicy(sizePolicy)
        self.t1_twgt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t1_twgt.setObjectName("t1_twgt")
        self.t1_twgt.setColumnCount(2)
        self.t1_twgt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t1_twgt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1_twgt.setHorizontalHeaderItem(1, item)
        self.t1_twgt.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.t1_twgt)
        self.t1_gb_trans = QtWidgets.QGroupBox(self.tab_balance)
        self.t1_gb_trans.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_gb_trans.sizePolicy().hasHeightForWidth())
        self.t1_gb_trans.setSizePolicy(sizePolicy)
        self.t1_gb_trans.setObjectName("t1_gb_trans")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.t1_gb_trans)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t1_chb_rot = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_rot.setObjectName("t1_chb_rot")
        self.horizontalLayout_11.addWidget(self.t1_chb_rot)
        self.t1_sb_rot = QtWidgets.QSpinBox(self.t1_gb_trans)
        self.t1_sb_rot.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t1_sb_rot.setMaximum(360)
        self.t1_sb_rot.setObjectName("t1_sb_rot")
        self.horizontalLayout_11.addWidget(self.t1_sb_rot)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.t1_chb_vertFlip = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_vertFlip.setObjectName("t1_chb_vertFlip")
        self.verticalLayout_7.addWidget(self.t1_chb_vertFlip)
        self.t1_chb_horFlip = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_horFlip.setObjectName("t1_chb_horFlip")
        self.verticalLayout_7.addWidget(self.t1_chb_horFlip)
        self.verticalLayout_8.addWidget(self.t1_gb_trans)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.t1_btn_next = QtWidgets.QPushButton(self.tab_balance)
        self.t1_btn_next.setObjectName("t1_btn_next")
        self.horizontalLayout_12.addWidget(self.t1_btn_next)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_balance, "")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.tab_view)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.t2_lwgt = QtWidgets.QListWidget(self.tab_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2_lwgt.sizePolicy().hasHeightForWidth())
        self.t2_lwgt.setSizePolicy(sizePolicy)
        self.t2_lwgt.setMaximumSize(QtCore.QSize(160, 16777215))
        self.t2_lwgt.setObjectName("t2_lwgt")
        self.verticalLayout_13.addWidget(self.t2_lwgt)
        self.t2_gb_info = QtWidgets.QGroupBox(self.tab_view)
        self.t2_gb_info.setEnabled(False)
        self.t2_gb_info.setMaximumSize(QtCore.QSize(160, 16777215))
        self.t2_gb_info.setObjectName("t2_gb_info")
        self.formLayout = QtWidgets.QFormLayout(self.t2_gb_info)
        self.formLayout.setObjectName("formLayout")
        self.t2_lbl_type = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_type.setObjectName("t2_lbl_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_type)
        self.t2_le_type = QtWidgets.QLineEdit(self.t2_gb_info)
        self.t2_le_type.setObjectName("t2_le_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.t2_le_type)
        self.t2_lbl_age = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_age.setObjectName("t2_lbl_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_age)
        self.t2_sb_age = QtWidgets.QSpinBox(self.t2_gb_info)
        self.t2_sb_age.setReadOnly(True)
        self.t2_sb_age.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t2_sb_age.setMaximum(1000)
        self.t2_sb_age.setObjectName("t2_sb_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2_sb_age)
        self.t2_lbl_sex = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_sex.setObjectName("t2_lbl_sex")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_sex)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.t2_radio_sexM = QtWidgets.QRadioButton(self.t2_gb_info)
        self.t2_radio_sexM.setObjectName("t2_radio_sexM")
        self.horizontalLayout_13.addWidget(self.t2_radio_sexM)
        self.t2_lbl_sexSep = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_sexSep.setObjectName("t2_lbl_sexSep")
        self.horizontalLayout_13.addWidget(self.t2_lbl_sexSep)
        self.t2_radio_sexF = QtWidgets.QRadioButton(self.t2_gb_info)
        self.t2_radio_sexF.setObjectName("t2_radio_sexF")
        self.horizontalLayout_13.addWidget(self.t2_radio_sexF)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.verticalLayout_13.addWidget(self.t2_gb_info)
        self.horizontalLayout_19.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 570))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t2_lytGrid = QtWidgets.QGridLayout()
        self.t2_lytGrid.setObjectName("t2_lytGrid")
        self.verticalLayout_9.addLayout(self.t2_lytGrid)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.t2_lbl_progress = QtWidgets.QLabel(self.tab_view)
        self.t2_lbl_progress.setObjectName("t2_lbl_progress")
        self.horizontalLayout_18.addWidget(self.t2_lbl_progress)
        self.t2_progress = QtWidgets.QProgressBar(self.tab_view)
        self.t2_progress.setProperty("value", 0)
        self.t2_progress.setObjectName("t2_progress")
        self.horizontalLayout_18.addWidget(self.t2_progress)
        self.t2_lbl_fake = QtWidgets.QLabel(self.tab_view)
        self.t2_lbl_fake.setText("")
        self.t2_lbl_fake.setObjectName("t2_lbl_fake")
        self.horizontalLayout_18.addWidget(self.t2_lbl_fake)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_view, "")
        self.tab_tensor = QtWidgets.QWidget()
        self.tab_tensor.setObjectName("tab_tensor")
        self.layoutWidget = QtWidgets.QWidget(self.tab_tensor)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 580, 391, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.t2_btn_next = QtWidgets.QPushButton(self.layoutWidget)
        self.t2_btn_next.setObjectName("t2_btn_next")
        self.horizontalLayout_14.addWidget(self.t2_btn_next)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_tensor)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 40, 591, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(40, 40, 131, 16))
        self.label_10.setObjectName("label_10")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 40, 160, 22))
        self.horizontalSlider.setMinimum(32)
        self.horizontalSlider.setMaximum(256)
        self.horizontalSlider.setSingleStep(32)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(370, 50, 42, 22))
        self.spinBox.setMaximum(256)
        self.spinBox.setObjectName("spinBox")
        self.tabWidget.addTab(self.tab_tensor, "")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.tabWidget.addTab(self.tab_train, "")
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_statistics)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.tab_statistics)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.t5_lytH_loss = QtWidgets.QVBoxLayout()
        self.t5_lytH_loss.setObjectName("t5_lytH_loss")
        self.verticalLayout_12.addLayout(self.t5_lytH_loss)
        self.label_13 = QtWidgets.QLabel(self.tab_statistics)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.t5_lytH_acc = QtWidgets.QVBoxLayout()
        self.t5_lytH_acc.setObjectName("t5_lytH_acc")
        self.verticalLayout_12.addLayout(self.t5_lytH_acc)
        self.label_14 = QtWidgets.QLabel(self.tab_statistics)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.t5_twgt = QtWidgets.QTableWidget(self.tab_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_twgt.sizePolicy().hasHeightForWidth())
        self.t5_twgt.setSizePolicy(sizePolicy)
        self.t5_twgt.setObjectName("t5_twgt")
        self.t5_twgt.setColumnCount(0)
        self.t5_twgt.setRowCount(0)
        self.verticalLayout_12.addWidget(self.t5_twgt)
        self.tabWidget.addTab(self.tab_statistics, "")
        self.tab_usage = QtWidgets.QWidget()
        self.tab_usage.setObjectName("tab_usage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_usage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_usage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.t6_le_openImg = QtWidgets.QLineEdit(self.groupBox_3)
        self.t6_le_openImg.setObjectName("t6_le_openImg")
        self.horizontalLayout_15.addWidget(self.t6_le_openImg)
        self.t6_btn_openImg = QtWidgets.QToolButton(self.groupBox_3)
        self.t6_btn_openImg.setObjectName("t6_btn_openImg")
        self.horizontalLayout_15.addWidget(self.t6_btn_openImg)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.t6_lbl_img = QtWidgets.QLabel(self.tab_usage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t6_lbl_img.sizePolicy().hasHeightForWidth())
        self.t6_lbl_img.setSizePolicy(sizePolicy)
        self.t6_lbl_img.setMinimumSize(QtCore.QSize(150, 150))
        self.t6_lbl_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t6_lbl_img.setObjectName("t6_lbl_img")
        self.verticalLayout_11.addWidget(self.t6_lbl_img)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.t6_btn_predict = QtWidgets.QPushButton(self.tab_usage)
        self.t6_btn_predict.setObjectName("t6_btn_predict")
        self.horizontalLayout_17.addWidget(self.t6_btn_predict)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.t6_lytH_results = QtWidgets.QVBoxLayout()
        self.t6_lytH_results.setObjectName("t6_lytH_results")
        self.verticalLayout_11.addLayout(self.t6_lytH_results)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.t6_btn_sameItems = QtWidgets.QPushButton(self.tab_usage)
        self.t6_btn_sameItems.setObjectName("t6_btn_sameItems")
        self.horizontalLayout_16.addWidget(self.t6_btn_sameItems)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_usage, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmdBtn_open = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_open.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_open.setCheckable(True)
        self.cmdBtn_open.setChecked(True)
        self.cmdBtn_open.setObjectName("cmdBtn_open")
        self.verticalLayout_2.addWidget(self.cmdBtn_open)
        self.cmdBtn_balance = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_balance.setEnabled(False)
        self.cmdBtn_balance.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_balance.setCheckable(True)
        self.cmdBtn_balance.setObjectName("cmdBtn_balance")
        self.verticalLayout_2.addWidget(self.cmdBtn_balance)
        self.cmdBtn_view = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_view.setEnabled(False)
        self.cmdBtn_view.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_view.setCheckable(True)
        self.cmdBtn_view.setObjectName("cmdBtn_view")
        self.verticalLayout_2.addWidget(self.cmdBtn_view)
        self.cmdBtn_tensor = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_tensor.setEnabled(False)
        self.cmdBtn_tensor.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_tensor.setCheckable(True)
        self.cmdBtn_tensor.setObjectName("cmdBtn_tensor")
        self.verticalLayout_2.addWidget(self.cmdBtn_tensor)
        self.cmdBtn_train = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_train.setEnabled(False)
        self.cmdBtn_train.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_train.setCheckable(True)
        self.cmdBtn_train.setObjectName("cmdBtn_train")
        self.verticalLayout_2.addWidget(self.cmdBtn_train)
        self.cmdBtn_statistics = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_statistics.setEnabled(False)
        self.cmdBtn_statistics.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_statistics.setCheckable(True)
        self.cmdBtn_statistics.setObjectName("cmdBtn_statistics")
        self.verticalLayout_2.addWidget(self.cmdBtn_statistics)
        self.cmdBtn_usage = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_usage.setEnabled(False)
        self.cmdBtn_usage.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_usage.setCheckable(True)
        self.cmdBtn_usage.setObjectName("cmdBtn_usage")
        self.verticalLayout_2.addWidget(self.cmdBtn_usage)
        self.debugBtn = QtWidgets.QPushButton(self.dockWidgetContents)
        self.debugBtn.setObjectName("debugBtn")
        self.verticalLayout_2.addWidget(self.debugBtn)
        spacerItem13 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.t0_sldr_trainSize.sliderMoved['int'].connect(self.t0_sb_trainSize.setValue)
        self.t0_radio_no.clicked['bool'].connect(self.t0_gb_manualSplit.setEnabled)
        self.t0_radio_yes.clicked['bool'].connect(self.t0_gb_manualSplit.setDisabled)
        self.t0_radio_yes.clicked['bool'].connect(self.t0_gb_autoSplit.setEnabled)
        self.t0_radio_no.clicked['bool'].connect(self.t0_gb_autoSplit.setDisabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_lbl_enrichMin.setEnabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_sb_enrichMin.setEnabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_twgt.setEnabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_gb_trans.setEnabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_gb_trans.setEnabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_gb_trans.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_twgt.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_lbl_enrichMin.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_sb_enrichMin.setDisabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_twgt.setDisabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_lbl_enrichMin.setDisabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_sb_enrichMin.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройка параметров нейросети"))
        self.groupBox.setTitle(_translate("MainWindow", "Файл метаданных"))
        self.t0_btn_openMeta.setText(_translate("MainWindow", "..."))
        self.t0_lbl_foundMeta_l.setText(_translate("MainWindow", "Найдено"))
        self.t0_lbl_foundMeta_r.setText(_translate("MainWindow", "изображений"))
        self.label.setText(_translate("MainWindow", "Изображения разделены на обучающую и тестовую выборку?"))
        self.t0_radio_yes.setText(_translate("MainWindow", "Да"))
        self.t0_radio_no.setText(_translate("MainWindow", "Нет"))
        self.t0_gb_autoSplit.setTitle(_translate("MainWindow", "Разделение уже произведено"))
        self.label_2.setText(_translate("MainWindow", "Train"))
        self.t0_btn_openTrain.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Test"))
        self.t0_btn_openTest.setText(_translate("MainWindow", "..."))
        self.t0_gb_manualSplit.setTitle(_translate("MainWindow", "Разделение"))
        self.label_7.setText(_translate("MainWindow", "Папка с изображениями"))
        self.t0_btn_openImg.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Объем тестовой выборки"))
        self.t0_sb_trainSize.setSuffix(_translate("MainWindow", " %"))
        self.t0_lbl_foundClasses_l.setText(_translate("MainWindow", "Найдено"))
        self.t0_lbl_foundClasses_r.setText(_translate("MainWindow", "классов"))
        self.t0_btn_classesInfo.setText(_translate("MainWindow", "?"))
        self.t0_lbl_trainPlot.setText(_translate("MainWindow", "Обучающая выборка"))
        self.t0_sb_countTrain_perc.setSuffix(_translate("MainWindow", " %"))
        self.label_4.setText(_translate("MainWindow", "/"))
        self.label_5.setText(_translate("MainWindow", "изображений"))
        self.t0_lbl_testPlot.setText(_translate("MainWindow", "Тестовая выборка"))
        self.t0_sb_countTest_perc.setSuffix(_translate("MainWindow", " %"))
        self.label_8.setText(_translate("MainWindow", "/"))
        self.label_9.setText(_translate("MainWindow", "изображений"))
        self.t0_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_open), _translate("MainWindow", "Открытие"))
        self.label_11.setText(_translate("MainWindow", "Баланс классов обучающей выборки:"))
        self.t1_radio_no_changes.setText(_translate("MainWindow", "Оставить без изменений"))
        self.t1_radio_enrichMin.setText(_translate("MainWindow", "Ограничить минимальным и обогатить в равной степени"))
        self.t1_lbl_enrichMin.setText(_translate("MainWindow", "Объем после обогащения"))
        self.t1_radio_enrichMax.setText(_translate("MainWindow", "Обогатить недостающие до максимума"))
        item = self.t1_twgt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        item = self.t1_twgt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Будет добавлено"))
        self.t1_gb_trans.setTitle(_translate("MainWindow", "Трансформации"))
        self.t1_chb_rot.setWhatsThis(_translate("MainWindow", "изображения будут повернуты на случайный угол в пределах выбранного"))
        self.t1_chb_rot.setText(_translate("MainWindow", "Вращения"))
        self.t1_sb_rot.setSuffix(_translate("MainWindow", " °"))
        self.t1_chb_vertFlip.setText(_translate("MainWindow", "Вертикальные отображения"))
        self.t1_chb_horFlip.setText(_translate("MainWindow", "Горизонтальные отображения"))
        self.t1_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_balance), _translate("MainWindow", "Баланс классов"))
        self.t2_gb_info.setTitle(_translate("MainWindow", "Инфо о пациенте"))
        self.t2_lbl_type.setText(_translate("MainWindow", "Источник"))
        self.t2_lbl_age.setText(_translate("MainWindow", "Возраст"))
        self.t2_lbl_sex.setText(_translate("MainWindow", "Пол"))
        self.t2_radio_sexM.setText(_translate("MainWindow", "М"))
        self.t2_lbl_sexSep.setText(_translate("MainWindow", "/"))
        self.t2_radio_sexF.setText(_translate("MainWindow", "Ж"))
        self.t2_lbl_progress.setText(_translate("MainWindow", "Открытие"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), _translate("MainWindow", "Просмотр"))
        self.t2_btn_next.setText(_translate("MainWindow", "Далее"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Изменение размера"))
        self.label_10.setText(_translate("MainWindow", "Размер изображений"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tensor), _translate("MainWindow", "Тензоры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "Обучение"))
        self.label_12.setText(_translate("MainWindow", "Кривая потерь (loss-curve)"))
        self.label_13.setText(_translate("MainWindow", "Accuracy curve"))
        self.label_14.setText(_translate("MainWindow", "Точность по классам"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_statistics), _translate("MainWindow", "Результаты"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Выберите изображение для классификации"))
        self.t6_btn_openImg.setText(_translate("MainWindow", "..."))
        self.t6_lbl_img.setText(_translate("MainWindow", "Image"))
        self.t6_btn_predict.setText(_translate("MainWindow", "Классфицировать"))
        self.t6_btn_sameItems.setText(_translate("MainWindow", "Посмотреть представителей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_usage), _translate("MainWindow", "Использование"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Доступные действия"))
        self.cmdBtn_open.setText(_translate("MainWindow", "Открытие"))
        self.cmdBtn_open.setDescription(_translate("MainWindow", "Выбор папки с изображениями. Train Test split"))
        self.cmdBtn_balance.setText(_translate("MainWindow", "Баланс классов"))
        self.cmdBtn_balance.setDescription(_translate("MainWindow", "Добавление/удаление изображений"))
        self.cmdBtn_view.setText(_translate("MainWindow", "Просмотр"))
        self.cmdBtn_view.setDescription(_translate("MainWindow", "Просмотр изображений итоговой обучающей выборки"))
        self.cmdBtn_tensor.setText(_translate("MainWindow", "Тензоры"))
        self.cmdBtn_tensor.setDescription(_translate("MainWindow", "Правила трансформации изображений в тензоры"))
        self.cmdBtn_train.setText(_translate("MainWindow", "Обучение"))
        self.cmdBtn_train.setDescription(_translate("MainWindow", "Выбор параметров обучения, архитектуры сети и ее параметров"))
        self.cmdBtn_statistics.setText(_translate("MainWindow", "Результаты"))
        self.cmdBtn_statistics.setDescription(_translate("MainWindow", "Кривая функции потерь. Статистика точности предсказания"))
        self.cmdBtn_usage.setText(_translate("MainWindow", "Использование"))
        self.cmdBtn_usage.setDescription(_translate("MainWindow", "Классификация изображений и просмотр результатов"))
        self.debugBtn.setText(_translate("MainWindow", "Debug"))

