# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dima\PyFiles\MedNN\qt_cpp_project\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(964, 764)
        MainWindow.setMinimumSize(QtCore.QSize(650, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(615, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_open = QtWidgets.QWidget()
        self.tab_open.setObjectName("tab_open")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_open)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab_open)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t0_le_openMeta = QtWidgets.QLineEdit(self.groupBox)
        self.t0_le_openMeta.setObjectName("t0_le_openMeta")
        self.horizontalLayout_2.addWidget(self.t0_le_openMeta)
        self.t0_btn_openMeta = QtWidgets.QToolButton(self.groupBox)
        self.t0_btn_openMeta.setObjectName("t0_btn_openMeta")
        self.horizontalLayout_2.addWidget(self.t0_btn_openMeta)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.t0_lbl_foundMeta_l = QtWidgets.QLabel(self.groupBox)
        self.t0_lbl_foundMeta_l.setEnabled(False)
        self.t0_lbl_foundMeta_l.setObjectName("t0_lbl_foundMeta_l")
        self.horizontalLayout_2.addWidget(self.t0_lbl_foundMeta_l)
        self.t0_sb_foundMeta = QtWidgets.QSpinBox(self.groupBox)
        self.t0_sb_foundMeta.setEnabled(False)
        self.t0_sb_foundMeta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t0_sb_foundMeta.setReadOnly(True)
        self.t0_sb_foundMeta.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_foundMeta.setProperty("showGroupSeparator", True)
        self.t0_sb_foundMeta.setObjectName("t0_sb_foundMeta")
        self.horizontalLayout_2.addWidget(self.t0_sb_foundMeta)
        self.t0_lbl_foundMeta_r = QtWidgets.QLabel(self.groupBox)
        self.t0_lbl_foundMeta_r.setEnabled(False)
        self.t0_lbl_foundMeta_r.setObjectName("t0_lbl_foundMeta_r")
        self.horizontalLayout_2.addWidget(self.t0_lbl_foundMeta_r)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.label = QtWidgets.QLabel(self.tab_open)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.t0_radio_yes = QtWidgets.QRadioButton(self.tab_open)
        self.t0_radio_yes.setObjectName("t0_radio_yes")
        self.horizontalLayout_3.addWidget(self.t0_radio_yes)
        self.t0_radio_no = QtWidgets.QRadioButton(self.tab_open)
        self.t0_radio_no.setObjectName("t0_radio_no")
        self.horizontalLayout_3.addWidget(self.t0_radio_no)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.t0_gb_autoSplit = QtWidgets.QGroupBox(self.tab_open)
        self.t0_gb_autoSplit.setEnabled(False)
        self.t0_gb_autoSplit.setObjectName("t0_gb_autoSplit")
        self.gridLayout = QtWidgets.QGridLayout(self.t0_gb_autoSplit)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.t0_gb_autoSplit)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.t0_le_openTrain = QtWidgets.QLineEdit(self.t0_gb_autoSplit)
        self.t0_le_openTrain.setObjectName("t0_le_openTrain")
        self.gridLayout.addWidget(self.t0_le_openTrain, 0, 1, 1, 1)
        self.t0_btn_openTrain = QtWidgets.QToolButton(self.t0_gb_autoSplit)
        self.t0_btn_openTrain.setObjectName("t0_btn_openTrain")
        self.gridLayout.addWidget(self.t0_btn_openTrain, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.t0_gb_autoSplit)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.t0_le_openTest = QtWidgets.QLineEdit(self.t0_gb_autoSplit)
        self.t0_le_openTest.setObjectName("t0_le_openTest")
        self.gridLayout.addWidget(self.t0_le_openTest, 1, 1, 1, 1)
        self.t0_btn_openTest = QtWidgets.QToolButton(self.t0_gb_autoSplit)
        self.t0_btn_openTest.setObjectName("t0_btn_openTest")
        self.gridLayout.addWidget(self.t0_btn_openTest, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.t0_gb_autoSplit)
        self.t0_gb_manualSplit = QtWidgets.QGroupBox(self.tab_open)
        self.t0_gb_manualSplit.setEnabled(False)
        self.t0_gb_manualSplit.setObjectName("t0_gb_manualSplit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.t0_gb_manualSplit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.t0_gb_manualSplit)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.t0_le_openImg = QtWidgets.QLineEdit(self.t0_gb_manualSplit)
        self.t0_le_openImg.setObjectName("t0_le_openImg")
        self.horizontalLayout_4.addWidget(self.t0_le_openImg)
        self.t0_btn_openImg = QtWidgets.QToolButton(self.t0_gb_manualSplit)
        self.t0_btn_openImg.setObjectName("t0_btn_openImg")
        self.horizontalLayout_4.addWidget(self.t0_btn_openImg)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.t0_gb_manualSplit)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.t0_sldr_testSize = QtWidgets.QSlider(self.t0_gb_manualSplit)
        self.t0_sldr_testSize.setMaximum(100)
        self.t0_sldr_testSize.setOrientation(QtCore.Qt.Horizontal)
        self.t0_sldr_testSize.setObjectName("t0_sldr_testSize")
        self.horizontalLayout_5.addWidget(self.t0_sldr_testSize)
        self.t0_sb_testSize = QtWidgets.QSpinBox(self.t0_gb_manualSplit)
        self.t0_sb_testSize.setReadOnly(True)
        self.t0_sb_testSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_testSize.setMaximum(100)
        self.t0_sb_testSize.setObjectName("t0_sb_testSize")
        self.horizontalLayout_5.addWidget(self.t0_sb_testSize)
        self.t0_btn_trainTestSplit = QtWidgets.QPushButton(self.t0_gb_manualSplit)
        self.t0_btn_trainTestSplit.setObjectName("t0_btn_trainTestSplit")
        self.horizontalLayout_5.addWidget(self.t0_btn_trainTestSplit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.t0_gb_manualSplit)
        self.line_2 = QtWidgets.QFrame(self.tab_open)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.t0_lbl_foundClasses_l = QtWidgets.QLabel(self.tab_open)
        self.t0_lbl_foundClasses_l.setObjectName("t0_lbl_foundClasses_l")
        self.horizontalLayout_6.addWidget(self.t0_lbl_foundClasses_l)
        self.t0_sb_foundClasses = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_foundClasses.setAlignment(QtCore.Qt.AlignCenter)
        self.t0_sb_foundClasses.setReadOnly(True)
        self.t0_sb_foundClasses.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_foundClasses.setObjectName("t0_sb_foundClasses")
        self.horizontalLayout_6.addWidget(self.t0_sb_foundClasses)
        self.t0_lbl_foundClasses_r = QtWidgets.QLabel(self.tab_open)
        self.t0_lbl_foundClasses_r.setObjectName("t0_lbl_foundClasses_r")
        self.horizontalLayout_6.addWidget(self.t0_lbl_foundClasses_r)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.t0_lwgt_classesInfo = QtWidgets.QListWidget(self.tab_open)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t0_lwgt_classesInfo.sizePolicy().hasHeightForWidth())
        self.t0_lwgt_classesInfo.setSizePolicy(sizePolicy)
        self.t0_lwgt_classesInfo.setMaximumSize(QtCore.QSize(160, 16777215))
        self.t0_lwgt_classesInfo.setObjectName("t0_lwgt_classesInfo")
        self.horizontalLayout_21.addWidget(self.t0_lwgt_classesInfo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.line_5 = QtWidgets.QFrame(self.tab_open)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.t0_lbl_trainPlot = QtWidgets.QLabel(self.tab_open)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t0_lbl_trainPlot.setFont(font)
        self.t0_lbl_trainPlot.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.t0_lbl_trainPlot.setObjectName("t0_lbl_trainPlot")
        self.verticalLayout_3.addWidget(self.t0_lbl_trainPlot)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.t0_sb_countTrain_perc = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTrain_perc.setReadOnly(True)
        self.t0_sb_countTrain_perc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTrain_perc.setMaximum(100)
        self.t0_sb_countTrain_perc.setObjectName("t0_sb_countTrain_perc")
        self.horizontalLayout.addWidget(self.t0_sb_countTrain_perc)
        self.label_4 = QtWidgets.QLabel(self.tab_open)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.t0_sb_countTrain = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTrain.setMinimumSize(QtCore.QSize(38, 0))
        self.t0_sb_countTrain.setReadOnly(True)
        self.t0_sb_countTrain.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTrain.setProperty("showGroupSeparator", True)
        self.t0_sb_countTrain.setSuffix("")
        self.t0_sb_countTrain.setPrefix("")
        self.t0_sb_countTrain.setObjectName("t0_sb_countTrain")
        self.horizontalLayout.addWidget(self.t0_sb_countTrain)
        self.label_5 = QtWidgets.QLabel(self.tab_open)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.tab_open)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.t0_lbl_testPlot = QtWidgets.QLabel(self.tab_open)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t0_lbl_testPlot.setFont(font)
        self.t0_lbl_testPlot.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.t0_lbl_testPlot.setObjectName("t0_lbl_testPlot")
        self.verticalLayout_4.addWidget(self.t0_lbl_testPlot)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.t0_sb_countTest_perc = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTest_perc.setReadOnly(True)
        self.t0_sb_countTest_perc.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTest_perc.setMaximum(100)
        self.t0_sb_countTest_perc.setObjectName("t0_sb_countTest_perc")
        self.horizontalLayout_7.addWidget(self.t0_sb_countTest_perc)
        self.label_8 = QtWidgets.QLabel(self.tab_open)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.t0_sb_countTest = QtWidgets.QSpinBox(self.tab_open)
        self.t0_sb_countTest.setMinimumSize(QtCore.QSize(38, 0))
        self.t0_sb_countTest.setReadOnly(True)
        self.t0_sb_countTest.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t0_sb_countTest.setProperty("showGroupSeparator", True)
        self.t0_sb_countTest.setSuffix("")
        self.t0_sb_countTest.setPrefix("")
        self.t0_sb_countTest.setObjectName("t0_sb_countTest")
        self.horizontalLayout_7.addWidget(self.t0_sb_countTest)
        self.label_9 = QtWidgets.QLabel(self.tab_open)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.t0_btn_next = QtWidgets.QPushButton(self.tab_open)
        self.t0_btn_next.setObjectName("t0_btn_next")
        self.horizontalLayout_8.addWidget(self.t0_btn_next)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_open, "")
        self.tab_balance = QtWidgets.QWidget()
        self.tab_balance.setObjectName("tab_balance")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_balance)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.tab_balance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.t1_lyt_plot = QtWidgets.QVBoxLayout()
        self.t1_lyt_plot.setObjectName("t1_lyt_plot")
        self.verticalLayout_8.addLayout(self.t1_lyt_plot)
        self.line_4 = QtWidgets.QFrame(self.tab_balance)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_8.addWidget(self.line_4)
        self.t1_radio_no_changes = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_no_changes.setObjectName("t1_radio_no_changes")
        self.verticalLayout_8.addWidget(self.t1_radio_no_changes)
        self.t1_radio_enrichMin = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_enrichMin.setObjectName("t1_radio_enrichMin")
        self.verticalLayout_8.addWidget(self.t1_radio_enrichMin)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.t1_lbl_enrichMin = QtWidgets.QLabel(self.tab_balance)
        self.t1_lbl_enrichMin.setEnabled(False)
        self.t1_lbl_enrichMin.setObjectName("t1_lbl_enrichMin")
        self.horizontalLayout_10.addWidget(self.t1_lbl_enrichMin)
        self.t1_sb_enrichMin = QtWidgets.QSpinBox(self.tab_balance)
        self.t1_sb_enrichMin.setEnabled(False)
        self.t1_sb_enrichMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t1_sb_enrichMin.setProperty("showGroupSeparator", True)
        self.t1_sb_enrichMin.setMaximum(10000)
        self.t1_sb_enrichMin.setObjectName("t1_sb_enrichMin")
        self.horizontalLayout_10.addWidget(self.t1_sb_enrichMin)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.t1_radio_enrichMax = QtWidgets.QRadioButton(self.tab_balance)
        self.t1_radio_enrichMax.setObjectName("t1_radio_enrichMax")
        self.verticalLayout_8.addWidget(self.t1_radio_enrichMax)
        self.t1_twgt = QtWidgets.QTableWidget(self.tab_balance)
        self.t1_twgt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_twgt.sizePolicy().hasHeightForWidth())
        self.t1_twgt.setSizePolicy(sizePolicy)
        self.t1_twgt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.t1_twgt.setObjectName("t1_twgt")
        self.t1_twgt.setColumnCount(2)
        self.t1_twgt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t1_twgt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t1_twgt.setHorizontalHeaderItem(1, item)
        self.t1_twgt.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.t1_twgt)
        self.t1_gb_trans = QtWidgets.QGroupBox(self.tab_balance)
        self.t1_gb_trans.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1_gb_trans.sizePolicy().hasHeightForWidth())
        self.t1_gb_trans.setSizePolicy(sizePolicy)
        self.t1_gb_trans.setObjectName("t1_gb_trans")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.t1_gb_trans)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t1_chb_rot = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_rot.setObjectName("t1_chb_rot")
        self.horizontalLayout_11.addWidget(self.t1_chb_rot)
        self.t1_sb_rot = QtWidgets.QSpinBox(self.t1_gb_trans)
        self.t1_sb_rot.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t1_sb_rot.setMaximum(360)
        self.t1_sb_rot.setObjectName("t1_sb_rot")
        self.horizontalLayout_11.addWidget(self.t1_sb_rot)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.t1_chb_vertFlip = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_vertFlip.setObjectName("t1_chb_vertFlip")
        self.verticalLayout_7.addWidget(self.t1_chb_vertFlip)
        self.t1_chb_horFlip = QtWidgets.QCheckBox(self.t1_gb_trans)
        self.t1_chb_horFlip.setObjectName("t1_chb_horFlip")
        self.verticalLayout_7.addWidget(self.t1_chb_horFlip)
        self.verticalLayout_8.addWidget(self.t1_gb_trans)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.t1_btn_next = QtWidgets.QPushButton(self.tab_balance)
        self.t1_btn_next.setObjectName("t1_btn_next")
        self.horizontalLayout_12.addWidget(self.t1_btn_next)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.tab_balance, "")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.t2_lwgt = QtWidgets.QListWidget(self.tab_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t2_lwgt.sizePolicy().hasHeightForWidth())
        self.t2_lwgt.setSizePolicy(sizePolicy)
        self.t2_lwgt.setMaximumSize(QtCore.QSize(160, 16777215))
        self.t2_lwgt.setObjectName("t2_lwgt")
        self.verticalLayout_13.addWidget(self.t2_lwgt)
        self.t2_gb_info = QtWidgets.QGroupBox(self.tab_view)
        self.t2_gb_info.setEnabled(False)
        self.t2_gb_info.setMaximumSize(QtCore.QSize(160, 16777215))
        self.t2_gb_info.setObjectName("t2_gb_info")
        self.formLayout = QtWidgets.QFormLayout(self.t2_gb_info)
        self.formLayout.setObjectName("formLayout")
        self.t2_lbl_type = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_type.setObjectName("t2_lbl_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_type)
        self.t2_le_type = QtWidgets.QLineEdit(self.t2_gb_info)
        self.t2_le_type.setObjectName("t2_le_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.t2_le_type)
        self.t2_lbl_age = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_age.setObjectName("t2_lbl_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_age)
        self.t2_sb_age = QtWidgets.QSpinBox(self.t2_gb_info)
        self.t2_sb_age.setReadOnly(True)
        self.t2_sb_age.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t2_sb_age.setMaximum(1000)
        self.t2_sb_age.setObjectName("t2_sb_age")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t2_sb_age)
        self.t2_lbl_sex = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_sex.setObjectName("t2_lbl_sex")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.t2_lbl_sex)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.t2_radio_sexM = QtWidgets.QRadioButton(self.t2_gb_info)
        self.t2_radio_sexM.setObjectName("t2_radio_sexM")
        self.horizontalLayout_13.addWidget(self.t2_radio_sexM)
        self.t2_lbl_sexSep = QtWidgets.QLabel(self.t2_gb_info)
        self.t2_lbl_sexSep.setObjectName("t2_lbl_sexSep")
        self.horizontalLayout_13.addWidget(self.t2_lbl_sexSep)
        self.t2_radio_sexF = QtWidgets.QRadioButton(self.t2_gb_info)
        self.t2_radio_sexF.setObjectName("t2_radio_sexF")
        self.horizontalLayout_13.addWidget(self.t2_radio_sexF)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.verticalLayout_13.addWidget(self.t2_gb_info)
        self.horizontalLayout_24.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 328, 615))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t2_lytGrid = QtWidgets.QGridLayout()
        self.t2_lytGrid.setObjectName("t2_lytGrid")
        self.verticalLayout_9.addLayout(self.t2_lytGrid)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.t2_lbl_progress = QtWidgets.QLabel(self.tab_view)
        self.t2_lbl_progress.setObjectName("t2_lbl_progress")
        self.horizontalLayout_18.addWidget(self.t2_lbl_progress)
        self.t2_progress = QtWidgets.QProgressBar(self.tab_view)
        self.t2_progress.setProperty("value", 0)
        self.t2_progress.setObjectName("t2_progress")
        self.horizontalLayout_18.addWidget(self.t2_progress)
        self.t2_lbl_fake = QtWidgets.QLabel(self.tab_view)
        self.t2_lbl_fake.setText("")
        self.t2_lbl_fake.setObjectName("t2_lbl_fake")
        self.horizontalLayout_18.addWidget(self.t2_lbl_fake)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_24.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.t2_btn_next = QtWidgets.QPushButton(self.tab_view)
        self.t2_btn_next.setObjectName("t2_btn_next")
        self.horizontalLayout_19.addWidget(self.t2_btn_next)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.tabWidget.addTab(self.tab_view, "")
        self.tab_tensor = QtWidgets.QWidget()
        self.tab_tensor.setObjectName("tab_tensor")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_tensor)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.t3_group_resize = QtWidgets.QGroupBox(self.tab_tensor)
        self.t3_group_resize.setObjectName("t3_group_resize")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.t3_group_resize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.t3_lbl_imgSize = QtWidgets.QLabel(self.t3_group_resize)
        self.t3_lbl_imgSize.setObjectName("t3_lbl_imgSize")
        self.horizontalLayout_23.addWidget(self.t3_lbl_imgSize)
        self.t3_sldr_imgSize = QtWidgets.QSlider(self.t3_group_resize)
        self.t3_sldr_imgSize.setMinimum(32)
        self.t3_sldr_imgSize.setMaximum(320)
        self.t3_sldr_imgSize.setSingleStep(32)
        self.t3_sldr_imgSize.setPageStep(32)
        self.t3_sldr_imgSize.setProperty("value", 300)
        self.t3_sldr_imgSize.setOrientation(QtCore.Qt.Horizontal)
        self.t3_sldr_imgSize.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.t3_sldr_imgSize.setObjectName("t3_sldr_imgSize")
        self.horizontalLayout_23.addWidget(self.t3_sldr_imgSize)
        self.t3_sb_imgSize = QtWidgets.QSpinBox(self.t3_group_resize)
        self.t3_sb_imgSize.setReadOnly(True)
        self.t3_sb_imgSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.t3_sb_imgSize.setMaximum(320)
        self.t3_sb_imgSize.setProperty("value", 300)
        self.t3_sb_imgSize.setObjectName("t3_sb_imgSize")
        self.horizontalLayout_23.addWidget(self.t3_sb_imgSize)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.t3_cb_resize = QtWidgets.QCheckBox(self.t3_group_resize)
        self.t3_cb_resize.setChecked(True)
        self.t3_cb_resize.setObjectName("t3_cb_resize")
        self.verticalLayout_16.addWidget(self.t3_cb_resize)
        self.t3_cb_centerCrop = QtWidgets.QCheckBox(self.t3_group_resize)
        self.t3_cb_centerCrop.setChecked(True)
        self.t3_cb_centerCrop.setObjectName("t3_cb_centerCrop")
        self.verticalLayout_16.addWidget(self.t3_cb_centerCrop)
        self.t3_cb_randomCrop = QtWidgets.QCheckBox(self.t3_group_resize)
        self.t3_cb_randomCrop.setObjectName("t3_cb_randomCrop")
        self.verticalLayout_16.addWidget(self.t3_cb_randomCrop)
        self.t3_randomResizeCrop = QtWidgets.QCheckBox(self.t3_group_resize)
        self.t3_randomResizeCrop.setObjectName("t3_randomResizeCrop")
        self.verticalLayout_16.addWidget(self.t3_randomResizeCrop)
        self.verticalLayout_23.addWidget(self.t3_group_resize)
        self.t3_group_flip = QtWidgets.QGroupBox(self.tab_tensor)
        self.t3_group_flip.setObjectName("t3_group_flip")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.t3_group_flip)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.t3_cb_randomHFlip = QtWidgets.QCheckBox(self.t3_group_flip)
        self.t3_cb_randomHFlip.setChecked(True)
        self.t3_cb_randomHFlip.setObjectName("t3_cb_randomHFlip")
        self.horizontalLayout_17.addWidget(self.t3_cb_randomHFlip)
        self.t3_sb_randomHFlip = QtWidgets.QDoubleSpinBox(self.t3_group_flip)
        self.t3_sb_randomHFlip.setMaximum(1.0)
        self.t3_sb_randomHFlip.setSingleStep(0.01)
        self.t3_sb_randomHFlip.setProperty("value", 0.5)
        self.t3_sb_randomHFlip.setObjectName("t3_sb_randomHFlip")
        self.horizontalLayout_17.addWidget(self.t3_sb_randomHFlip)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.t3_cb_randomVFlip = QtWidgets.QCheckBox(self.t3_group_flip)
        self.t3_cb_randomVFlip.setObjectName("t3_cb_randomVFlip")
        self.horizontalLayout_26.addWidget(self.t3_cb_randomVFlip)
        self.t3_sb_randomVFlip = QtWidgets.QDoubleSpinBox(self.t3_group_flip)
        self.t3_sb_randomVFlip.setMaximum(1.0)
        self.t3_sb_randomVFlip.setSingleStep(0.01)
        self.t3_sb_randomVFlip.setProperty("value", 0.5)
        self.t3_sb_randomVFlip.setObjectName("t3_sb_randomVFlip")
        self.horizontalLayout_26.addWidget(self.t3_sb_randomVFlip)
        self.verticalLayout_15.addLayout(self.horizontalLayout_26)
        self.verticalLayout_23.addWidget(self.t3_group_flip)
        self.t3_group_colors = QtWidgets.QGroupBox(self.tab_tensor)
        self.t3_group_colors.setObjectName("t3_group_colors")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.t3_group_colors)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.t3_group_colorJitter = QtWidgets.QGroupBox(self.t3_group_colors)
        self.t3_group_colorJitter.setCheckable(True)
        self.t3_group_colorJitter.setChecked(False)
        self.t3_group_colorJitter.setObjectName("t3_group_colorJitter")
        self.formLayout_2 = QtWidgets.QFormLayout(self.t3_group_colorJitter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.t3_group_colorJitter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.t3_sb_cjBrightness = QtWidgets.QDoubleSpinBox(self.t3_group_colorJitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3_sb_cjBrightness.sizePolicy().hasHeightForWidth())
        self.t3_sb_cjBrightness.setSizePolicy(sizePolicy)
        self.t3_sb_cjBrightness.setMaximum(1.0)
        self.t3_sb_cjBrightness.setSingleStep(0.01)
        self.t3_sb_cjBrightness.setObjectName("t3_sb_cjBrightness")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.t3_sb_cjBrightness)
        self.label_15 = QtWidgets.QLabel(self.t3_group_colorJitter)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.t3_sb_cjContrast = QtWidgets.QDoubleSpinBox(self.t3_group_colorJitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3_sb_cjContrast.sizePolicy().hasHeightForWidth())
        self.t3_sb_cjContrast.setSizePolicy(sizePolicy)
        self.t3_sb_cjContrast.setMaximum(1.0)
        self.t3_sb_cjContrast.setSingleStep(0.01)
        self.t3_sb_cjContrast.setObjectName("t3_sb_cjContrast")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t3_sb_cjContrast)
        self.label_16 = QtWidgets.QLabel(self.t3_group_colorJitter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.t3_sb_cjSaturation = QtWidgets.QDoubleSpinBox(self.t3_group_colorJitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3_sb_cjSaturation.sizePolicy().hasHeightForWidth())
        self.t3_sb_cjSaturation.setSizePolicy(sizePolicy)
        self.t3_sb_cjSaturation.setMaximum(1.0)
        self.t3_sb_cjSaturation.setSingleStep(0.01)
        self.t3_sb_cjSaturation.setObjectName("t3_sb_cjSaturation")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.t3_sb_cjSaturation)
        self.label_17 = QtWidgets.QLabel(self.t3_group_colorJitter)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.t3_sb_cjHue = QtWidgets.QDoubleSpinBox(self.t3_group_colorJitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3_sb_cjHue.sizePolicy().hasHeightForWidth())
        self.t3_sb_cjHue.setSizePolicy(sizePolicy)
        self.t3_sb_cjHue.setMaximum(1.0)
        self.t3_sb_cjHue.setSingleStep(0.01)
        self.t3_sb_cjHue.setObjectName("t3_sb_cjHue")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.t3_sb_cjHue)
        self.verticalLayout_20.addWidget(self.t3_group_colorJitter)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.t3_cb_grayScale = QtWidgets.QCheckBox(self.t3_group_colors)
        self.t3_cb_grayScale.setObjectName("t3_cb_grayScale")
        self.horizontalLayout_27.addWidget(self.t3_cb_grayScale)
        self.t3_sb_grayScale = QtWidgets.QSpinBox(self.t3_group_colors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t3_sb_grayScale.sizePolicy().hasHeightForWidth())
        self.t3_sb_grayScale.setSizePolicy(sizePolicy)
        self.t3_sb_grayScale.setMaximum(3)
        self.t3_sb_grayScale.setObjectName("t3_sb_grayScale")
        self.horizontalLayout_27.addWidget(self.t3_sb_grayScale)
        self.verticalLayout_20.addLayout(self.horizontalLayout_27)
        self.verticalLayout_23.addWidget(self.t3_group_colors)
        self.t3_group_rotation = QtWidgets.QGroupBox(self.tab_tensor)
        self.t3_group_rotation.setObjectName("t3_group_rotation")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.t3_group_rotation)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.t3_cb_randomRotation = QtWidgets.QCheckBox(self.t3_group_rotation)
        self.t3_cb_randomRotation.setObjectName("t3_cb_randomRotation")
        self.horizontalLayout_28.addWidget(self.t3_cb_randomRotation)
        self.t3_sb_randomRotation = QtWidgets.QSpinBox(self.t3_group_rotation)
        self.t3_sb_randomRotation.setPrefix("")
        self.t3_sb_randomRotation.setMaximum(180)
        self.t3_sb_randomRotation.setObjectName("t3_sb_randomRotation")
        self.horizontalLayout_28.addWidget(self.t3_sb_randomRotation)
        self.verticalLayout_21.addLayout(self.horizontalLayout_28)
        self.verticalLayout_23.addWidget(self.t3_group_rotation)
        self.t3_group_norm = QtWidgets.QGroupBox(self.tab_tensor)
        self.t3_group_norm.setCheckable(True)
        self.t3_group_norm.setObjectName("t3_group_norm")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.t3_group_norm)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.t3_lbl_mean = QtWidgets.QLabel(self.t3_group_norm)
        self.t3_lbl_mean.setObjectName("t3_lbl_mean")
        self.horizontalLayout_29.addWidget(self.t3_lbl_mean)
        self.t3_sb_mean1 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_mean1.setDecimals(3)
        self.t3_sb_mean1.setMaximum(1.0)
        self.t3_sb_mean1.setSingleStep(0.001)
        self.t3_sb_mean1.setProperty("value", 0.485)
        self.t3_sb_mean1.setObjectName("t3_sb_mean1")
        self.horizontalLayout_29.addWidget(self.t3_sb_mean1)
        self.t3_sb_mean2 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_mean2.setDecimals(3)
        self.t3_sb_mean2.setMaximum(1.0)
        self.t3_sb_mean2.setSingleStep(0.001)
        self.t3_sb_mean2.setProperty("value", 0.456)
        self.t3_sb_mean2.setObjectName("t3_sb_mean2")
        self.horizontalLayout_29.addWidget(self.t3_sb_mean2)
        self.t3_sb_mean3 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_mean3.setDecimals(3)
        self.t3_sb_mean3.setMaximum(1.0)
        self.t3_sb_mean3.setSingleStep(0.001)
        self.t3_sb_mean3.setProperty("value", 0.406)
        self.t3_sb_mean3.setObjectName("t3_sb_mean3")
        self.horizontalLayout_29.addWidget(self.t3_sb_mean3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.t3_lbl_std = QtWidgets.QLabel(self.t3_group_norm)
        self.t3_lbl_std.setObjectName("t3_lbl_std")
        self.horizontalLayout_30.addWidget(self.t3_lbl_std)
        self.t3_sb_std1 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_std1.setDecimals(3)
        self.t3_sb_std1.setMaximum(1.0)
        self.t3_sb_std1.setSingleStep(0.001)
        self.t3_sb_std1.setProperty("value", 0.229)
        self.t3_sb_std1.setObjectName("t3_sb_std1")
        self.horizontalLayout_30.addWidget(self.t3_sb_std1)
        self.t3_sb_std2 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_std2.setDecimals(3)
        self.t3_sb_std2.setMaximum(1.0)
        self.t3_sb_std2.setSingleStep(0.001)
        self.t3_sb_std2.setProperty("value", 0.224)
        self.t3_sb_std2.setObjectName("t3_sb_std2")
        self.horizontalLayout_30.addWidget(self.t3_sb_std2)
        self.t3_sb_std3 = QtWidgets.QDoubleSpinBox(self.t3_group_norm)
        self.t3_sb_std3.setDecimals(3)
        self.t3_sb_std3.setMaximum(1.0)
        self.t3_sb_std3.setSingleStep(0.001)
        self.t3_sb_std3.setProperty("value", 0.225)
        self.t3_sb_std3.setObjectName("t3_sb_std3")
        self.horizontalLayout_30.addWidget(self.t3_sb_std3)
        self.verticalLayout_22.addLayout(self.horizontalLayout_30)
        self.verticalLayout_23.addWidget(self.t3_group_norm)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.t3_btn_next = QtWidgets.QPushButton(self.tab_tensor)
        self.t3_btn_next.setObjectName("t3_btn_next")
        self.horizontalLayout_14.addWidget(self.t3_btn_next)
        self.verticalLayout_23.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_tensor, "")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_train)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_train)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.t4_cb_inceptionV3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_inceptionV3.setObjectName("t4_cb_inceptionV3")
        self.gridLayout_2.addWidget(self.t4_cb_inceptionV3, 1, 0, 1, 1)
        self.t4_cb_googleNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_googleNet.setObjectName("t4_cb_googleNet")
        self.gridLayout_2.addWidget(self.t4_cb_googleNet, 0, 3, 1, 1)
        self.t4_cb_shuffleNetV2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_shuffleNetV2.setObjectName("t4_cb_shuffleNetV2")
        self.gridLayout_2.addWidget(self.t4_cb_shuffleNetV2, 1, 1, 1, 1)
        self.t4_cb_denseNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_denseNet.setObjectName("t4_cb_denseNet")
        self.gridLayout_2.addWidget(self.t4_cb_denseNet, 0, 2, 1, 1)
        self.t4_cb_mobileNetV2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_mobileNetV2.setObjectName("t4_cb_mobileNetV2")
        self.gridLayout_2.addWidget(self.t4_cb_mobileNetV2, 1, 2, 1, 1)
        self.t4_cb_resNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_resNet.setObjectName("t4_cb_resNet")
        self.gridLayout_2.addWidget(self.t4_cb_resNet, 2, 0, 1, 1)
        self.t4_cb_wideResNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_wideResNet.setObjectName("t4_cb_wideResNet")
        self.gridLayout_2.addWidget(self.t4_cb_wideResNet, 2, 2, 1, 1)
        self.t4_cb_resNetXt = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_resNetXt.setObjectName("t4_cb_resNetXt")
        self.gridLayout_2.addWidget(self.t4_cb_resNetXt, 2, 1, 1, 1)
        self.t4_cb_vgg = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_vgg.setObjectName("t4_cb_vgg")
        self.gridLayout_2.addWidget(self.t4_cb_vgg, 0, 1, 1, 1)
        self.t4_cb_alexNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_alexNet.setObjectName("t4_cb_alexNet")
        self.gridLayout_2.addWidget(self.t4_cb_alexNet, 0, 0, 1, 1)
        self.t4_cb_mnasNet = QtWidgets.QCheckBox(self.groupBox_2)
        self.t4_cb_mnasNet.setObjectName("t4_cb_mnasNet")
        self.gridLayout_2.addWidget(self.t4_cb_mnasNet, 1, 3, 1, 1)
        self.verticalLayout_24.addWidget(self.groupBox_2)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.t4_lbl_layersCnt = QtWidgets.QLabel(self.widget)
        self.t4_lbl_layersCnt.setEnabled(False)
        self.t4_lbl_layersCnt.setObjectName("t4_lbl_layersCnt")
        self.horizontalLayout_31.addWidget(self.t4_lbl_layersCnt)
        self.t4_combo_layersCnt = QtWidgets.QComboBox(self.widget)
        self.t4_combo_layersCnt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t4_combo_layersCnt.sizePolicy().hasHeightForWidth())
        self.t4_combo_layersCnt.setSizePolicy(sizePolicy)
        self.t4_combo_layersCnt.setObjectName("t4_combo_layersCnt")
        self.t4_combo_layersCnt.addItem("")
        self.t4_combo_layersCnt.addItem("")
        self.t4_combo_layersCnt.addItem("")
        self.t4_combo_layersCnt.addItem("")
        self.t4_combo_layersCnt.addItem("")
        self.horizontalLayout_31.addWidget(self.t4_combo_layersCnt)
        self.verticalLayout_24.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.t4_lbl_epochsCnt = QtWidgets.QLabel(self.widget)
        self.t4_lbl_epochsCnt.setObjectName("t4_lbl_epochsCnt")
        self.horizontalLayout_32.addWidget(self.t4_lbl_epochsCnt)
        self.t4_sldr_epochsCnt = QtWidgets.QSlider(self.widget)
        self.t4_sldr_epochsCnt.setOrientation(QtCore.Qt.Horizontal)
        self.t4_sldr_epochsCnt.setObjectName("t4_sldr_epochsCnt")
        self.horizontalLayout_32.addWidget(self.t4_sldr_epochsCnt)
        self.t4_sb_epochsCnt = QtWidgets.QSpinBox(self.widget)
        self.t4_sb_epochsCnt.setObjectName("t4_sb_epochsCnt")
        self.horizontalLayout_32.addWidget(self.t4_sb_epochsCnt)
        self.verticalLayout_24.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.t4_lbl_batchSize = QtWidgets.QLabel(self.widget)
        self.t4_lbl_batchSize.setObjectName("t4_lbl_batchSize")
        self.horizontalLayout_33.addWidget(self.t4_lbl_batchSize)
        self.t4_sldr_batchSize = QtWidgets.QSlider(self.widget)
        self.t4_sldr_batchSize.setMaximum(100)
        self.t4_sldr_batchSize.setOrientation(QtCore.Qt.Horizontal)
        self.t4_sldr_batchSize.setObjectName("t4_sldr_batchSize")
        self.horizontalLayout_33.addWidget(self.t4_sldr_batchSize)
        self.t4_sb_batchSize = QtWidgets.QSpinBox(self.widget)
        self.t4_sb_batchSize.setMaximum(100)
        self.t4_sb_batchSize.setObjectName("t4_sb_batchSize")
        self.horizontalLayout_33.addWidget(self.t4_sb_batchSize)
        self.verticalLayout_24.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.t4_lbl_loss = QtWidgets.QLabel(self.widget)
        self.t4_lbl_loss.setObjectName("t4_lbl_loss")
        self.horizontalLayout_34.addWidget(self.t4_lbl_loss)
        self.t4_combo_loss = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t4_combo_loss.sizePolicy().hasHeightForWidth())
        self.t4_combo_loss.setSizePolicy(sizePolicy)
        self.t4_combo_loss.setObjectName("t4_combo_loss")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.t4_combo_loss.addItem("")
        self.horizontalLayout_34.addWidget(self.t4_combo_loss)
        self.verticalLayout_24.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.t4_lbl_optim = QtWidgets.QLabel(self.widget)
        self.t4_lbl_optim.setObjectName("t4_lbl_optim")
        self.horizontalLayout_35.addWidget(self.t4_lbl_optim)
        self.t4_combo_optim = QtWidgets.QComboBox(self.widget)
        self.t4_combo_optim.setObjectName("t4_combo_optim")
        self.t4_combo_optim.addItem("")
        self.t4_combo_optim.addItem("")
        self.horizontalLayout_35.addWidget(self.t4_combo_optim)
        self.t4_lbl_optim_2 = QtWidgets.QLabel(self.widget)
        self.t4_lbl_optim_2.setObjectName("t4_lbl_optim_2")
        self.horizontalLayout_35.addWidget(self.t4_lbl_optim_2)
        self.t4_sb_learningRate = QtWidgets.QDoubleSpinBox(self.widget)
        self.t4_sb_learningRate.setDecimals(3)
        self.t4_sb_learningRate.setMaximum(1.0)
        self.t4_sb_learningRate.setSingleStep(0.001)
        self.t4_sb_learningRate.setObjectName("t4_sb_learningRate")
        self.horizontalLayout_35.addWidget(self.t4_sb_learningRate)
        self.verticalLayout_24.addLayout(self.horizontalLayout_35)
        self.t4_cb_lrscheduler = QtWidgets.QCheckBox(self.widget)
        self.t4_cb_lrscheduler.setObjectName("t4_cb_lrscheduler")
        self.verticalLayout_24.addWidget(self.t4_cb_lrscheduler)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_24.addWidget(self.line_6)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem11)
        self.t4_btn_train = QtWidgets.QPushButton(self.widget)
        self.t4_btn_train.setObjectName("t4_btn_train")
        self.horizontalLayout_36.addWidget(self.t4_btn_train)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem12)
        self.verticalLayout_24.addLayout(self.horizontalLayout_36)
        self.widget1 = QtWidgets.QWidget(self.splitter_2)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.t4_progress = QtWidgets.QProgressBar(self.widget1)
        self.t4_progress.setProperty("value", 0)
        self.t4_progress.setObjectName("t4_progress")
        self.verticalLayout_14.addWidget(self.t4_progress)
        self.t4_te = QtWidgets.QTextEdit(self.widget1)
        self.t4_te.setObjectName("t4_te")
        self.verticalLayout_14.addWidget(self.t4_te)
        self.verticalLayout_25.addWidget(self.splitter_2)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self.t4_btn_next = QtWidgets.QPushButton(self.tab_train)
        self.t4_btn_next.setObjectName("t4_btn_next")
        self.horizontalLayout_22.addWidget(self.t4_btn_next)
        self.verticalLayout_25.addLayout(self.horizontalLayout_22)
        self.tabWidget.addTab(self.tab_train, "")
        self.tab_statistics = QtWidgets.QWidget()
        self.tab_statistics.setObjectName("tab_statistics")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tab_statistics)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.t5_lbl_nnPath = QtWidgets.QLabel(self.tab_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_lbl_nnPath.sizePolicy().hasHeightForWidth())
        self.t5_lbl_nnPath.setSizePolicy(sizePolicy)
        self.t5_lbl_nnPath.setObjectName("t5_lbl_nnPath")
        self.horizontalLayout_20.addWidget(self.t5_lbl_nnPath)
        self.t5_le_nnPath = QtWidgets.QLineEdit(self.tab_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_le_nnPath.sizePolicy().hasHeightForWidth())
        self.t5_le_nnPath.setSizePolicy(sizePolicy)
        self.t5_le_nnPath.setObjectName("t5_le_nnPath")
        self.horizontalLayout_20.addWidget(self.t5_le_nnPath)
        self.t5_btn_nnPath = QtWidgets.QToolButton(self.tab_statistics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_btn_nnPath.sizePolicy().hasHeightForWidth())
        self.t5_btn_nnPath.setSizePolicy(sizePolicy)
        self.t5_btn_nnPath.setObjectName("t5_btn_nnPath")
        self.horizontalLayout_20.addWidget(self.t5_btn_nnPath)
        self.t5_combo = QtWidgets.QComboBox(self.tab_statistics)
        self.t5_combo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_combo.sizePolicy().hasHeightForWidth())
        self.t5_combo.setSizePolicy(sizePolicy)
        self.t5_combo.setMinimumSize(QtCore.QSize(160, 0))
        self.t5_combo.setObjectName("t5_combo")
        self.horizontalLayout_20.addWidget(self.t5_combo)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.splitter = QtWidgets.QSplitter(self.tab_statistics)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.t5_lytH_loss = QtWidgets.QVBoxLayout()
        self.t5_lytH_loss.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.t5_lytH_loss.setObjectName("t5_lytH_loss")
        self.verticalLayout_12.addLayout(self.t5_lytH_loss)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.t5_lytH_acc = QtWidgets.QVBoxLayout()
        self.t5_lytH_acc.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.t5_lytH_acc.setObjectName("t5_lytH_acc")
        self.verticalLayout_12.addLayout(self.t5_lytH_acc)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        self.t5_twgt = QtWidgets.QTableWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t5_twgt.sizePolicy().hasHeightForWidth())
        self.t5_twgt.setSizePolicy(sizePolicy)
        self.t5_twgt.setObjectName("t5_twgt")
        self.t5_twgt.setColumnCount(2)
        self.t5_twgt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.t5_twgt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.t5_twgt.setHorizontalHeaderItem(1, item)
        self.verticalLayout_18.addWidget(self.t5_twgt)
        self.verticalLayout_19.addWidget(self.splitter)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.t5_btn_save = QtWidgets.QPushButton(self.tab_statistics)
        self.t5_btn_save.setObjectName("t5_btn_save")
        self.horizontalLayout_25.addWidget(self.t5_btn_save)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem14)
        self.t5_btn_next = QtWidgets.QPushButton(self.tab_statistics)
        self.t5_btn_next.setObjectName("t5_btn_next")
        self.horizontalLayout_25.addWidget(self.t5_btn_next)
        self.verticalLayout_19.addLayout(self.horizontalLayout_25)
        self.tabWidget.addTab(self.tab_statistics, "")
        self.tab_usage = QtWidgets.QWidget()
        self.tab_usage.setObjectName("tab_usage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_usage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_usage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.t6_le_openImg = QtWidgets.QLineEdit(self.groupBox_3)
        self.t6_le_openImg.setObjectName("t6_le_openImg")
        self.horizontalLayout_15.addWidget(self.t6_le_openImg)
        self.t6_btn_openImg = QtWidgets.QToolButton(self.groupBox_3)
        self.t6_btn_openImg.setObjectName("t6_btn_openImg")
        self.horizontalLayout_15.addWidget(self.t6_btn_openImg)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.t6_lbl_img = QtWidgets.QLabel(self.tab_usage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t6_lbl_img.sizePolicy().hasHeightForWidth())
        self.t6_lbl_img.setSizePolicy(sizePolicy)
        self.t6_lbl_img.setMinimumSize(QtCore.QSize(200, 200))
        self.t6_lbl_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t6_lbl_img.setObjectName("t6_lbl_img")
        self.verticalLayout_11.addWidget(self.t6_lbl_img)
        self.t6_lytH_results = QtWidgets.QVBoxLayout()
        self.t6_lytH_results.setObjectName("t6_lytH_results")
        self.verticalLayout_11.addLayout(self.t6_lytH_results)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.t6_btn_sameItems = QtWidgets.QPushButton(self.tab_usage)
        self.t6_btn_sameItems.setObjectName("t6_btn_sameItems")
        self.horizontalLayout_16.addWidget(self.t6_btn_sameItems)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_usage, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmdBtn_open = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_open.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_open.setCheckable(True)
        self.cmdBtn_open.setChecked(True)
        self.cmdBtn_open.setObjectName("cmdBtn_open")
        self.verticalLayout_2.addWidget(self.cmdBtn_open)
        self.cmdBtn_balance = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_balance.setEnabled(False)
        self.cmdBtn_balance.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_balance.setCheckable(True)
        self.cmdBtn_balance.setObjectName("cmdBtn_balance")
        self.verticalLayout_2.addWidget(self.cmdBtn_balance)
        self.cmdBtn_view = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_view.setEnabled(False)
        self.cmdBtn_view.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_view.setCheckable(True)
        self.cmdBtn_view.setObjectName("cmdBtn_view")
        self.verticalLayout_2.addWidget(self.cmdBtn_view)
        self.cmdBtn_tensor = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_tensor.setEnabled(False)
        self.cmdBtn_tensor.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_tensor.setCheckable(True)
        self.cmdBtn_tensor.setObjectName("cmdBtn_tensor")
        self.verticalLayout_2.addWidget(self.cmdBtn_tensor)
        self.cmdBtn_train = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_train.setEnabled(False)
        self.cmdBtn_train.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_train.setCheckable(True)
        self.cmdBtn_train.setObjectName("cmdBtn_train")
        self.verticalLayout_2.addWidget(self.cmdBtn_train)
        self.cmdBtn_statistics = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_statistics.setEnabled(False)
        self.cmdBtn_statistics.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_statistics.setCheckable(True)
        self.cmdBtn_statistics.setObjectName("cmdBtn_statistics")
        self.verticalLayout_2.addWidget(self.cmdBtn_statistics)
        self.cmdBtn_usage = QtWidgets.QCommandLinkButton(self.dockWidgetContents)
        self.cmdBtn_usage.setEnabled(False)
        self.cmdBtn_usage.setMinimumSize(QtCore.QSize(230, 70))
        self.cmdBtn_usage.setCheckable(True)
        self.cmdBtn_usage.setObjectName("cmdBtn_usage")
        self.verticalLayout_2.addWidget(self.cmdBtn_usage)
        spacerItem17 = QtWidgets.QSpacerItem(20, 84, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.t0_sldr_testSize.sliderMoved['int'].connect(self.t0_sb_testSize.setValue)
        self.t0_radio_no.clicked['bool'].connect(self.t0_gb_manualSplit.setEnabled)
        self.t0_radio_yes.clicked['bool'].connect(self.t0_gb_manualSplit.setDisabled)
        self.t0_radio_yes.clicked['bool'].connect(self.t0_gb_autoSplit.setEnabled)
        self.t0_radio_no.clicked['bool'].connect(self.t0_gb_autoSplit.setDisabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_lbl_enrichMin.setEnabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_sb_enrichMin.setEnabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_twgt.setEnabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_gb_trans.setEnabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_gb_trans.setEnabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_gb_trans.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_twgt.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_lbl_enrichMin.setDisabled)
        self.t1_radio_no_changes.clicked['bool'].connect(self.t1_sb_enrichMin.setDisabled)
        self.t1_radio_enrichMin.clicked['bool'].connect(self.t1_twgt.setDisabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_lbl_enrichMin.setDisabled)
        self.t1_radio_enrichMax.clicked['bool'].connect(self.t1_sb_enrichMin.setDisabled)
        self.t3_sldr_imgSize.valueChanged['int'].connect(self.t3_sb_imgSize.setValue)
        self.t4_sldr_epochsCnt.valueChanged['int'].connect(self.t4_sb_epochsCnt.setValue)
        self.t4_sldr_batchSize.valueChanged['int'].connect(self.t4_sb_batchSize.setValue)
        self.t4_cb_resNet.clicked['bool'].connect(self.t4_combo_layersCnt.setEnabled)
        self.t4_cb_resNetXt.clicked['bool'].connect(self.t4_combo_layersCnt.setEnabled)
        self.t4_cb_wideResNet.clicked['bool'].connect(self.t4_combo_layersCnt.setEnabled)
        self.t4_cb_alexNet.clicked['bool'].connect(self.t4_combo_layersCnt.setDisabled)
        self.t4_cb_vgg.clicked['bool'].connect(self.t4_combo_layersCnt.setEnabled)
        self.t4_cb_inceptionV3.clicked['bool'].connect(self.t4_combo_layersCnt.setDisabled)
        self.t4_cb_alexNet.clicked['bool'].connect(self.t4_lbl_layersCnt.setDisabled)
        self.t4_cb_vgg.clicked['bool'].connect(self.t4_lbl_layersCnt.setEnabled)
        self.t4_cb_inceptionV3.clicked['bool'].connect(self.t4_lbl_layersCnt.setDisabled)
        self.t4_cb_resNet.clicked['bool'].connect(self.t4_lbl_layersCnt.setEnabled)
        self.t4_cb_resNetXt.clicked['bool'].connect(self.t4_lbl_layersCnt.setEnabled)
        self.t4_cb_wideResNet.clicked['bool'].connect(self.t4_lbl_layersCnt.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройка параметров нейросети"))
        self.groupBox.setTitle(_translate("MainWindow", "Файл метаданных"))
        self.t0_btn_openMeta.setText(_translate("MainWindow", "..."))
        self.t0_lbl_foundMeta_l.setText(_translate("MainWindow", "Найдено"))
        self.t0_lbl_foundMeta_r.setText(_translate("MainWindow", "изображений"))
        self.label.setText(_translate("MainWindow", "Изображения разделены на обучающую и тестовую выборку?"))
        self.t0_radio_yes.setText(_translate("MainWindow", "Да"))
        self.t0_radio_no.setText(_translate("MainWindow", "Нет"))
        self.t0_gb_autoSplit.setTitle(_translate("MainWindow", "Разделение уже произведено"))
        self.label_2.setText(_translate("MainWindow", "Train"))
        self.t0_btn_openTrain.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Test"))
        self.t0_btn_openTest.setText(_translate("MainWindow", "..."))
        self.t0_gb_manualSplit.setTitle(_translate("MainWindow", "Разделение"))
        self.label_7.setText(_translate("MainWindow", "Папка с изображениями"))
        self.t0_btn_openImg.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Объем тестовой выборки"))
        self.t0_sb_testSize.setSuffix(_translate("MainWindow", " %"))
        self.t0_btn_trainTestSplit.setText(_translate("MainWindow", "Разбить"))
        self.t0_lbl_foundClasses_l.setText(_translate("MainWindow", "Найдено"))
        self.t0_lbl_foundClasses_r.setText(_translate("MainWindow", "классов:"))
        self.t0_lbl_trainPlot.setText(_translate("MainWindow", "Обучающая выборка"))
        self.t0_sb_countTrain_perc.setSuffix(_translate("MainWindow", " %"))
        self.label_4.setText(_translate("MainWindow", "/"))
        self.label_5.setText(_translate("MainWindow", "изображений"))
        self.t0_lbl_testPlot.setText(_translate("MainWindow", "Тестовая выборка"))
        self.t0_sb_countTest_perc.setSuffix(_translate("MainWindow", " %"))
        self.label_8.setText(_translate("MainWindow", "/"))
        self.label_9.setText(_translate("MainWindow", "изображений"))
        self.t0_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_open), _translate("MainWindow", "Открытие"))
        self.label_11.setText(_translate("MainWindow", "Баланс классов обучающей выборки:"))
        self.t1_radio_no_changes.setText(_translate("MainWindow", "Оставить без изменений"))
        self.t1_radio_enrichMin.setText(_translate("MainWindow", "Ограничить минимальным и обогатить в равной степени"))
        self.t1_lbl_enrichMin.setText(_translate("MainWindow", "Объем после обогащения"))
        self.t1_radio_enrichMax.setText(_translate("MainWindow", "Обогатить недостающие до максимума"))
        item = self.t1_twgt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        item = self.t1_twgt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Будет добавлено"))
        self.t1_gb_trans.setTitle(_translate("MainWindow", "Трансформации"))
        self.t1_chb_rot.setWhatsThis(_translate("MainWindow", "изображения будут повернуты на случайный угол в пределах выбранного"))
        self.t1_chb_rot.setText(_translate("MainWindow", "Вращения"))
        self.t1_sb_rot.setSuffix(_translate("MainWindow", " °"))
        self.t1_chb_vertFlip.setText(_translate("MainWindow", "Вертикальные отображения"))
        self.t1_chb_horFlip.setText(_translate("MainWindow", "Горизонтальные отображения"))
        self.t1_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_balance), _translate("MainWindow", "Баланс классов"))
        self.t2_gb_info.setTitle(_translate("MainWindow", "Инфо о пациенте"))
        self.t2_lbl_type.setText(_translate("MainWindow", "Источник"))
        self.t2_lbl_age.setText(_translate("MainWindow", "Возраст"))
        self.t2_lbl_sex.setText(_translate("MainWindow", "Пол"))
        self.t2_radio_sexM.setText(_translate("MainWindow", "М"))
        self.t2_lbl_sexSep.setText(_translate("MainWindow", "/"))
        self.t2_radio_sexF.setText(_translate("MainWindow", "Ж"))
        self.t2_lbl_progress.setText(_translate("MainWindow", "Открытие"))
        self.t2_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), _translate("MainWindow", "Просмотр"))
        self.t3_group_resize.setTitle(_translate("MainWindow", "Обрезка"))
        self.t3_lbl_imgSize.setText(_translate("MainWindow", "Размер"))
        self.t3_sldr_imgSize.setToolTip(_translate("MainWindow", "Для Inception минимум 299"))
        self.t3_sb_imgSize.setToolTip(_translate("MainWindow", "Для Inception минимум 299"))
        self.t3_cb_resize.setText(_translate("MainWindow", "Растянуть (Resize)"))
        self.t3_cb_centerCrop.setText(_translate("MainWindow", "Вырезать в центре (CenterCrop)"))
        self.t3_cb_randomCrop.setText(_translate("MainWindow", "Вырезать в случайном месте (RandomCrop)"))
        self.t3_randomResizeCrop.setToolTip(_translate("MainWindow", "Популярно при использовании Inception"))
        self.t3_randomResizeCrop.setText(_translate("MainWindow", "Обрезать случайным размером со случайным соотношением сторон  (RandomResizedCrop)"))
        self.t3_group_flip.setTitle(_translate("MainWindow", "Отображения"))
        self.t3_cb_randomHFlip.setText(_translate("MainWindow", "Случайное отображение по горизонтали (RandomHorizontalFlip)"))
        self.t3_sb_randomHFlip.setPrefix(_translate("MainWindow", "Вероятность "))
        self.t3_cb_randomVFlip.setText(_translate("MainWindow", "Случайное отображение по вертикали (RandomVerticalFlip)"))
        self.t3_sb_randomVFlip.setPrefix(_translate("MainWindow", "Вероятность "))
        self.t3_group_colors.setTitle(_translate("MainWindow", "Цвета"))
        self.t3_group_colorJitter.setTitle(_translate("MainWindow", "Случайно менять яркость/контраст/цветовой тон (ColorJitter)"))
        self.label_10.setText(_translate("MainWindow", "Яркость"))
        self.label_15.setText(_translate("MainWindow", "Контраст"))
        self.label_16.setText(_translate("MainWindow", "Насыщенность"))
        self.label_17.setText(_translate("MainWindow", "Цветовой тон"))
        self.t3_cb_grayScale.setText(_translate("MainWindow", "Чернобелое (Grayscale)"))
        self.t3_sb_grayScale.setToolTip(_translate("MainWindow", "Количество выходных каналов"))
        self.t3_group_rotation.setTitle(_translate("MainWindow", "Вращения"))
        self.t3_cb_randomRotation.setText(_translate("MainWindow", "Случайный поворот (RandomRotation)"))
        self.t3_sb_randomRotation.setSuffix(_translate("MainWindow", " °"))
        self.t3_group_norm.setTitle(_translate("MainWindow", "Нормализация"))
        self.t3_lbl_mean.setText(_translate("MainWindow", "Среднее"))
        self.t3_lbl_std.setText(_translate("MainWindow", "СКО"))
        self.t3_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tensor), _translate("MainWindow", "Тензоры"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Архитектура"))
        self.t4_cb_inceptionV3.setText(_translate("MainWindow", "Inception_v3"))
        self.t4_cb_googleNet.setText(_translate("MainWindow", "GoogLeNet"))
        self.t4_cb_shuffleNetV2.setText(_translate("MainWindow", "ShuffleNet_v2"))
        self.t4_cb_denseNet.setText(_translate("MainWindow", "DenseNet"))
        self.t4_cb_mobileNetV2.setText(_translate("MainWindow", "MobileNet_v2"))
        self.t4_cb_resNet.setText(_translate("MainWindow", "ResNet"))
        self.t4_cb_wideResNet.setText(_translate("MainWindow", "WideResNet"))
        self.t4_cb_resNetXt.setText(_translate("MainWindow", "ResNeXt"))
        self.t4_cb_vgg.setText(_translate("MainWindow", "VGG"))
        self.t4_cb_alexNet.setText(_translate("MainWindow", "AlexNet"))
        self.t4_cb_mnasNet.setText(_translate("MainWindow", "MNASNet"))
        self.t4_lbl_layersCnt.setText(_translate("MainWindow", "Количество слоев"))
        self.t4_combo_layersCnt.setItemText(0, _translate("MainWindow", "18"))
        self.t4_combo_layersCnt.setItemText(1, _translate("MainWindow", "34"))
        self.t4_combo_layersCnt.setItemText(2, _translate("MainWindow", "50"))
        self.t4_combo_layersCnt.setItemText(3, _translate("MainWindow", "101"))
        self.t4_combo_layersCnt.setItemText(4, _translate("MainWindow", "152"))
        self.t4_lbl_epochsCnt.setText(_translate("MainWindow", "Количество эпох"))
        self.t4_lbl_batchSize.setText(_translate("MainWindow", "Размер батча"))
        self.t4_lbl_loss.setText(_translate("MainWindow", "Функция потерь"))
        self.t4_combo_loss.setItemText(0, _translate("MainWindow", "CrossEntropyLoss - combines nn.LogSoftmax() and nn.NLLLoss()"))
        self.t4_combo_loss.setItemText(1, _translate("MainWindow", "L1Loss - measures the mean absolute error (MAE) between each element"))
        self.t4_combo_loss.setItemText(2, _translate("MainWindow", "MSELoss - measures the mean squared error (squared L2 norm) between each element"))
        self.t4_combo_loss.setItemText(3, _translate("MainWindow", "CTCLoss - Connectionist Temporal Classification loss"))
        self.t4_combo_loss.setItemText(4, _translate("MainWindow", "NLLLoss -  negative log likelihood loss"))
        self.t4_combo_loss.setItemText(5, _translate("MainWindow", "PoissonNLLLoss - Negative log likelihood loss with Poisson distribution"))
        self.t4_combo_loss.setItemText(6, _translate("MainWindow", "KLDivLoss - Kullback-Leibler divergence Loss"))
        self.t4_combo_loss.setItemText(7, _translate("MainWindow", "BCELoss - criterion that measures the Binary Cross Entropy"))
        self.t4_lbl_optim.setText(_translate("MainWindow", "Оптимизатор"))
        self.t4_combo_optim.setItemText(0, _translate("MainWindow", "SGD"))
        self.t4_combo_optim.setItemText(1, _translate("MainWindow", "Adam"))
        self.t4_lbl_optim_2.setText(_translate("MainWindow", "Скорость обучения"))
        self.t4_cb_lrscheduler.setText(_translate("MainWindow", "Динамическая скорость обучения"))
        self.t4_btn_train.setText(_translate("MainWindow", "Обучить"))
        self.t4_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "Обучение"))
        self.t5_lbl_nnPath.setText(_translate("MainWindow", "Путь нейросети"))
        self.t5_btn_nnPath.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "кривая потерь (loss-curve)"))
        self.label_13.setText(_translate("MainWindow", "кривая точности (accuracy-curve)"))
        self.label_14.setText(_translate("MainWindow", "Точность по классам"))
        item = self.t5_twgt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Класс"))
        item = self.t5_twgt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Точность (accuracy)"))
        self.t5_btn_save.setText(_translate("MainWindow", "Сохранить"))
        self.t5_btn_next.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_statistics), _translate("MainWindow", "Результаты"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Выберите изображение для классификации"))
        self.t6_btn_openImg.setText(_translate("MainWindow", "..."))
        self.t6_lbl_img.setText(_translate("MainWindow", "Image"))
        self.t6_btn_sameItems.setText(_translate("MainWindow", "Посмотреть представителей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_usage), _translate("MainWindow", "Использование"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Доступные действия"))
        self.cmdBtn_open.setText(_translate("MainWindow", "Открытие"))
        self.cmdBtn_open.setDescription(_translate("MainWindow", "Выбор папки с изображениями. Train Test split"))
        self.cmdBtn_balance.setText(_translate("MainWindow", "Баланс классов"))
        self.cmdBtn_balance.setDescription(_translate("MainWindow", "Добавление/удаление изображений"))
        self.cmdBtn_view.setText(_translate("MainWindow", "Просмотр"))
        self.cmdBtn_view.setDescription(_translate("MainWindow", "Просмотр изображений итоговой обучающей выборки"))
        self.cmdBtn_tensor.setText(_translate("MainWindow", "Тензоры"))
        self.cmdBtn_tensor.setDescription(_translate("MainWindow", "Правила трансформации изображений в тензоры"))
        self.cmdBtn_train.setText(_translate("MainWindow", "Обучение"))
        self.cmdBtn_train.setDescription(_translate("MainWindow", "Выбор параметров обучения, архитектуры сети и ее параметров"))
        self.cmdBtn_statistics.setText(_translate("MainWindow", "Результаты"))
        self.cmdBtn_statistics.setDescription(_translate("MainWindow", "Кривая функции потерь. Статистика точности предсказания"))
        self.cmdBtn_usage.setText(_translate("MainWindow", "Использование"))
        self.cmdBtn_usage.setDescription(_translate("MainWindow", "Классификация изображений и просмотр результатов"))

