# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.imageFolderLE = QtWidgets.QLineEdit(self.centralwidget)
        self.imageFolderLE.setReadOnly(True)
        self.imageFolderLE.setObjectName("imageFolderLE")
        self.gridLayout.addWidget(self.imageFolderLE, 1, 1, 1, 1)
        self.imageFoldelLbl = QtWidgets.QLabel(self.centralwidget)
        self.imageFoldelLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imageFoldelLbl.setObjectName("imageFoldelLbl")
        self.gridLayout.addWidget(self.imageFoldelLbl, 1, 0, 1, 1)
        self.openImageFolderBtn = QtWidgets.QToolButton(self.centralwidget)
        self.openImageFolderBtn.setObjectName("openImageFolderBtn")
        self.gridLayout.addWidget(self.openImageFolderBtn, 1, 2, 1, 1)
        self.csvFileLE = QtWidgets.QLineEdit(self.centralwidget)
        self.csvFileLE.setReadOnly(True)
        self.csvFileLE.setObjectName("csvFileLE")
        self.gridLayout.addWidget(self.csvFileLE, 0, 1, 1, 1)
        self.openCsvBtn = QtWidgets.QToolButton(self.centralwidget)
        self.openCsvBtn.setObjectName("openCsvBtn")
        self.gridLayout.addWidget(self.openCsvBtn, 0, 2, 1, 1)
        self.csvFileLbl = QtWidgets.QLabel(self.centralwidget)
        self.csvFileLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.csvFileLbl.setObjectName("csvFileLbl")
        self.gridLayout.addWidget(self.csvFileLbl, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imgView = QtWidgets.QGraphicsView(self.tabView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgView.sizePolicy().hasHeightForWidth())
        self.imgView.setSizePolicy(sizePolicy)
        self.imgView.setMinimumSize(QtCore.QSize(1000, 0))
        self.imgView.setObjectName("imgView")
        self.horizontalLayout_2.addWidget(self.imgView)
        self.metaLyt = QtWidgets.QFormLayout()
        self.metaLyt.setObjectName("metaLyt")
        self.nameLbl = QtWidgets.QLabel(self.tabView)
        self.nameLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLbl.setObjectName("nameLbl")
        self.metaLyt.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLbl)
        self.nameLE = QtWidgets.QLineEdit(self.tabView)
        self.nameLE.setObjectName("nameLE")
        self.metaLyt.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLE)
        self.sizeLbl = QtWidgets.QLabel(self.tabView)
        self.sizeLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeLbl.setObjectName("sizeLbl")
        self.metaLyt.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sizeLbl)
        self.sizeHLyt = QtWidgets.QHBoxLayout()
        self.sizeHLyt.setObjectName("sizeHLyt")
        self.sizeWSb = QtWidgets.QSpinBox(self.tabView)
        self.sizeWSb.setReadOnly(True)
        self.sizeWSb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sizeWSb.setMaximum(601)
        self.sizeWSb.setObjectName("sizeWSb")
        self.sizeHLyt.addWidget(self.sizeWSb)
        self.sizeXLbl = QtWidgets.QLabel(self.tabView)
        self.sizeXLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sizeXLbl.setObjectName("sizeXLbl")
        self.sizeHLyt.addWidget(self.sizeXLbl)
        self.sizeHSb = QtWidgets.QSpinBox(self.tabView)
        self.sizeHSb.setReadOnly(True)
        self.sizeHSb.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sizeHSb.setMaximum(601)
        self.sizeHSb.setObjectName("sizeHSb")
        self.sizeHLyt.addWidget(self.sizeHSb)
        self.metaLyt.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.sizeHLyt)
        self.sexLbl = QtWidgets.QLabel(self.tabView)
        self.sexLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sexLbl.setObjectName("sexLbl")
        self.metaLyt.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sexLbl)
        self.sexHLyt = QtWidgets.QHBoxLayout()
        self.sexHLyt.setObjectName("sexHLyt")
        self.sexMRb = QtWidgets.QRadioButton(self.tabView)
        self.sexMRb.setObjectName("sexMRb")
        self.sexHLyt.addWidget(self.sexMRb)
        self.sexSepLbl = QtWidgets.QLabel(self.tabView)
        self.sexSepLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sexSepLbl.setObjectName("sexSepLbl")
        self.sexHLyt.addWidget(self.sexSepLbl)
        self.sexFRb = QtWidgets.QRadioButton(self.tabView)
        self.sexFRb.setObjectName("sexFRb")
        self.sexHLyt.addWidget(self.sexFRb)
        self.metaLyt.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.sexHLyt)
        self.agelbl = QtWidgets.QLabel(self.tabView)
        self.agelbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.agelbl.setObjectName("agelbl")
        self.metaLyt.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.agelbl)
        self.ageSB = QtWidgets.QSpinBox(self.tabView)
        self.ageSB.setReadOnly(True)
        self.ageSB.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ageSB.setMaximum(601)
        self.ageSB.setObjectName("ageSB")
        self.metaLyt.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ageSB)
        self.diagnosisLbl = QtWidgets.QLabel(self.tabView)
        self.diagnosisLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diagnosisLbl.setObjectName("diagnosisLbl")
        self.metaLyt.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.diagnosisLbl)
        self.diagnosisLE = QtWidgets.QLineEdit(self.tabView)
        self.diagnosisLE.setObjectName("diagnosisLE")
        self.metaLyt.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.diagnosisLE)
        self.diagnosisConfLbl = QtWidgets.QLabel(self.tabView)
        self.diagnosisConfLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diagnosisConfLbl.setObjectName("diagnosisConfLbl")
        self.metaLyt.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.diagnosisConfLbl)
        self.diagnosisConfLe = QtWidgets.QLineEdit(self.tabView)
        self.diagnosisConfLe.setObjectName("diagnosisConfLe")
        self.metaLyt.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.diagnosisConfLe)
        self.horizontalLayout_2.addLayout(self.metaLyt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabView, "")
        self.tabTable = QtWidgets.QWidget()
        self.tabTable.setObjectName("tabTable")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabTable)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.tabTable)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.tabWidget.addTab(self.tabTable, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.learnBtn = QtWidgets.QPushButton(self.centralwidget)
        self.learnBtn.setObjectName("learnBtn")
        self.horizontalLayout.addWidget(self.learnBtn)
        self.usageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.usageBtn.setEnabled(False)
        self.usageBtn.setObjectName("usageBtn")
        self.horizontalLayout.addWidget(self.usageBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1282, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNavigation = QtWidgets.QMenu(self.menubar)
        self.menuNavigation.setObjectName("menuNavigation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuNavigation.addAction(self.actionNext)
        self.menuNavigation.addAction(self.actionPrevious)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNavigation.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.openCsvBtn.clicked.connect(self.actionOpen_File.trigger)
        self.openImageFolderBtn.clicked.connect(self.actionOpen_Folder.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Классификация изображений меланомы"))
        self.imageFoldelLbl.setText(_translate("MainWindow", "Папка изображений"))
        self.openImageFolderBtn.setText(_translate("MainWindow", "..."))
        self.openCsvBtn.setText(_translate("MainWindow", "..."))
        self.csvFileLbl.setText(_translate("MainWindow", "CSV файл"))
        self.nameLbl.setText(_translate("MainWindow", "Название"))
        self.sizeLbl.setText(_translate("MainWindow", "Размер"))
        self.sizeXLbl.setText(_translate("MainWindow", "x"))
        self.sexLbl.setText(_translate("MainWindow", "Пол"))
        self.sexMRb.setText(_translate("MainWindow", "М"))
        self.sexSepLbl.setText(_translate("MainWindow", "/"))
        self.sexFRb.setText(_translate("MainWindow", "Ж"))
        self.agelbl.setText(_translate("MainWindow", "Возраст"))
        self.diagnosisLbl.setText(_translate("MainWindow", "Диагноз"))
        self.diagnosisConfLbl.setText(_translate("MainWindow", "Подтверждение диагноза"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabView), _translate("MainWindow", "Просмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTable), _translate("MainWindow", "Таблица"))
        self.learnBtn.setText(_translate("MainWindow", "Обучение"))
        self.usageBtn.setText(_translate("MainWindow", "Классификация"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuNavigation.setTitle(_translate("MainWindow", "Навигация"))
        self.actionNext.setText(_translate("MainWindow", "Следующее"))
        self.actionNext.setToolTip(_translate("MainWindow", "Следующее изображение"))
        self.actionNext.setShortcut(_translate("MainWindow", "Right"))
        self.actionPrevious.setText(_translate("MainWindow", "Предыдущее"))
        self.actionPrevious.setToolTip(_translate("MainWindow", "Предыдущее изображение"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Left"))
        self.actionQuit.setText(_translate("MainWindow", "Выход"))
        self.actionQuit.setToolTip(_translate("MainWindow", "Выход из программы"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen_File.setText(_translate("MainWindow", "Открыть CSV"))
        self.actionOpen_File.setToolTip(_translate("MainWindow", "Открыть файл с признаками изображений"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Открыть папку"))
        self.actionOpen_Folder.setToolTip(_translate("MainWindow", "Открыть папку с изображениями"))
        self.actionOpen_Folder.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
